name: 🚀 Deploy ASP.NET API to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: 🚀 Deploy using SSH with password
        env:
          SSH_USER: ${{ secrets.VPS_USER }}
          SSH_PASS: ${{ secrets.VPS_SSH_PASS }}
          SSH_HOST: ${{ secrets.VPS_HOST }}
          APP_NAME: ${{ secrets.APP_NAME }}
        run: |
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
            set -e
            cd ~
            if [ ! -d TaskManager ]; then
              git clone https://github.com/${{ github.repository }}.git TaskManager
            fi
            cd TaskManager
            git pull origin main
            docker build -t '${{ secrets.APP_NAME }}' .
            docker stop '${{ secrets.APP_NAME }}' || true
            docker rm '${{ secrets.APP_NAME }}' || true
            docker run -d --restart unless-stopped --name '${{ secrets.APP_NAME }}' -p 8080:80 '${{ secrets.APP_NAME }}'
          "